### PR TITLE
bug/issue 59 apply semantic HTML to header social links list

### LINKED ISSUE #59: header component social icons are not using semantically correct list HTML
## Summary

The current header component which renders a [set of social icons](https://github.com/ProjectEvergreen/www.greenwoodjs.dev/blob/main/src/components/header/header.js#L35) but it does not seem to be contained in a correctly wrapping parent element.
Screenshot 2024-06-17 at 11 54 03 AM
```html
<div class="social-tray">
  <li class="social-icon">
    <a href="https://github.com/ProjectEvergreen/greenwood" title="GitHub">
      ${githubIcon}
    </a>
  </li>

  <li class="social-icon">
    <a href="https://discord.gg/bsy9jvWh" title="Discord">
      ${discordIcon}
    </a>
  </li>

  <li class="social-icon">
    <a href="https://twitter.com/PrjEvergreen" title="Twitter">
      ${twitterIcon}
    </a>
  </li>
</div>
```
----

The issue is that these are `<li>` items but they are not actually in a `<ul>` or a `<ol>`, which they probably should be?

## Details
My guess is it should work just the same if the `<div>` is changed to a `<ul>`?
```html
<ul class="social-tray">
  <!-- ... -->
</ul>
```

### PR DESCRIPTION
**Pull request by monyasau**
replace div parent of li elements with ul to enhance page semantics

## Related Issue
Resolves #59

## Summary of Changes

 Replace the div parent of li element with ul tags to improve page ranking

1. [x] Replace div with appropriate ul tag

### CODE REVIEW

**Review by thescientist13 — COMMENTED** [review]
Thanks for this @monyasau 🙏 

Looks like we just need to tweak the [selector here in our header spec](https://github.com/ProjectEvergreen/www.greenwoodjs.dev/blob/main/src/components/header/header.spec.js#L57) to get is [passing again](https://github.com/ProjectEvergreen/www.greenwoodjs.dev/actions/runs/9551744371/job/26333350897?pr=61), then this looks good to me!

**Comment by monyasau** [comment]
ok i dont understand, what do i need to change

**Comment by thescientist13** [comment]
The selector in the test case needs to be more specific.  I just played around with it now and changing the selector on that line to this should work
```js
const links = header.shadowRoot.querySelectorAll("nav ul.nav-bar-menu li a");
```

**Review by thescientist13 — APPROVED** [review]
Just updated the test case and now everything looks good.

Thank you!

**Pull request merged**
