### PR TITLE
enhancement/issue 71 acquire svgs for all assets

### LINKED ISSUE #71: use SVGs for all logos and icons
## Summary

A couple of our [image assets](https://github.com/ProjectEvergreen/www.greenwoodjs.dev/tree/main/src/assets) that could probably be SVGs are not, and instead are PNGs.

Would like to at least acquire the following as SVGs
1. node
1. netlify
1. vercel (seems to just be an SVG "wrapper" around a base64 encoded image)
1. WCC (seems to just be an SVG "wrapper" around a base64 encoded image - @thescientist13 to tracking down)

## Details

Will then want to refactor platform component to use inline `<svg>` instead of ``, which should then address this Lighthouse item(s) all related to images
Screenshot 2024-08-18 at 2 56 26 PM
Screenshot 2024-08-18 at 2 59 44 PM
Screenshot 2024-08-18 at 2 59 39 PM

### PR DESCRIPTION
**Pull request by Auhseh**
## Related Issue

resolves #71 

## Summary of Changes
1. Added all the required svgs
1. Swapped out images for SVGs for _Run Anywhere_ content

## TODOs
1. [x] Update Netlify, Vercel, and NodeJS paths in _Run Anywhere_ section / component
1. [x] Remove old images
1. [x] Re-run Lighthouse report
1. [x] Update WCC usage in the _Build with Friends_ section / component (can come in a follow up PR)

### CODE REVIEW

**Review by thescientist13 — CHANGES_REQUESTED** [review]
Hey @Auhseh , thanks for this.

Have some feedback for this one if you are able to (otherwise i don't mind making these changes)

1.  Let's follow the file naming convention of the project just to keep things consistent (this should get the build passing):
    - _Nodejs.svg_ -> _nodejs.svg_
    - _Vercel.svg_ -> _vercel.svg_
    - (I would use `git mv` for these since I think git has some issues with case sensitivity when renaming)
1.  I appreciate the effort, but let's remove the WCC icon for now.  I've already reached out to the original designer to get a proper SVG export so I can take care of that one (since the one here looks a little jagged / choppy).  👍 
1. Can we update the image references on the home page to swap out the PNGs with the new SVGs.  (all but the WCC icon are used in the _Run Anywhere_ section)

Thanks again!

----

Also, this branch seemed pretty far behind `main` so I did a rebase to get the latest home page code where these icons are being used just to better validate the changes overall when we make the swap, so just keep that in mind when pushing / pulling with git.

**Review by thescientist13 — APPROVED** [review]
Had a chance to get some of the feedback in and things are looking good now!  Should be getting the updated WCC logo soon, but if I don't get it in a couple of days, we can totally merge this and I can submit a follow PR just for WCC.

Thanks again @Auhseh 🤝

**Review by thescientist13 — COMMENTED** [review]
In touch with the designer now and should have a new WCC logo SVG soon, but if it's not available by end of the week, I'll merge this as is and follow up with the WCC logo on its own.

**Review by thescientist13 — APPROVED** [review]
Awesome, the updated WCC logo has landed!  Will give this a couple days for any final reviews and otherwise will merge by end of the week.

Thanks again @Auhseh !

**Comment by Auhseh** [comment]
Looks good 🚀

**Pull request merged**
